[defaultboot]
default = linux

[linux]
target = /boot
kernel = /boot/vmlinuz
ramdisk = /boot/initramfs.img
parameters = "root=LABEL=rootfs rd.dasd=0.0.0200 rd.zfcp=0.0.4000,0x5005076305ffd123,0x4023 rd.net=qeth,0.0.0600,layer2=1"
